matrix:
  include:
    - name: "Shared module build (util, classpath)"
      language: java
      script: ./gradlew shared:build
    
    - name: "Language server tests"
      language: java
      script: ./gradlew server:test -i
      
    - name: "Language server executable"
      language: java
      script: ./gradlew server:installDist
    
    - name: "VSCode extension (Node.js)"
      language: node_js
      install:
        - npm install
        - npm run compile
      script: echo "npm tests temporarily disabled"
