matrix:
  include:
    - language: java
      install: ./gradlew install
      script: ./gradlew build -i
    
    - language: node_js
      install:
        - npm install
        - npm run compile
      script: echo "npm tests temporarily disabled"
