language: java
jdk:
  - openjdk8
  - openjdk11
env: NODE_VERSION=8
before_install: nvm install $NODE_VERSION

jobs:
  include:
    - stage: "Shared Module"
      name: "Build"
      script: ./gradlew :shared:build
    - name: "Tests"
      script: ./gradlew :shared:test -i
    - stage: "Language Server"
      name: "Tests"
      script: ./gradlew :server:test -i
    - name: "Executable"
      script: ./gradlew :server:installDist
    - stage: "Editor extensions"
      name: "VSCode"
      script: ./gradlew :editors:vscode:build
    - name: "Atom"
      script: ./gradlew :editors:atom:build
